import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawn,spawnSync} from 'node:child_process';import {createServer} from 'node:http';
import {ConfigService} from '../dist/config/config-service.js';import {connect,request} from '../dist/cli/client.js';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'skf-m27-cli-'));const cfg=path.join(root,'配置 空格');const env={...process.env};for(const k of Object.keys(env))if(/^SKF_|^XIAOLIU_|KEY|SECRET|TOKEN|PASSWORD/.test(k))delete env[k];Object.assign(env,{SKF_CONFIG_DIR:cfg,SKF_SKIP_ENV:'1',SKF_LEARNING:'0',SKF_MEMORY_SEMANTIC:'0',SKF_OPENCLAW_BRIDGE:'0',SKF_BUDGET_MODE:'local-only'});
const run=(args,value='')=>new Promise(resolve=>{const p=spawn(process.execPath,['dist/cli.js',...args,'--config-dir',cfg],{env,stdio:['pipe','pipe','pipe']});p.stdin.end(value);let out='',err='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',b=>err+=b);p.on('exit',code=>resolve({code,out,err}));});
let server,info;const config=new ConfigService({configDir:cfg,env});
test.after(async()=>{if(info)try{await request(info,'POST','/v1/stop',{});}catch{}if(server)await new Promise(r=>server.close(r));await new Promise(r=>setTimeout(r,600));fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:300});});
test('CLI rejects secret arguments and non-TTY onboarding without echo or hanging',async()=>{const a=await run(['model','key','replace','local','--api-key','fixture-value']);assert.equal(a.code,1);assert.equal(a.err.trim(),'SECRET_ARGUMENT_FORBIDDEN');assert.ok(!a.out.includes('fixture-value'));const b=await run(['onboard']);assert.equal(b.code,1);assert.match(b.err,/TTY_REQUIRED/);const c=await run(['start','--headless']);assert.equal(c.code,1);assert.match(c.err,/SETUP_REQUIRED/);});
test('headless manager starts one existing core, fake local chat, pinned models, safe stop, no secret export',async()=>{
  const calls=[];server=createServer(async(req,res)=>{let body='';for await(const b of req)body+=b;res.setHeader('Content-Type','application/json');if(req.url.endsWith('/models'))res.end(JSON.stringify({data:[{id:'fixture-a'},{id:'fixture-b'}]}));else{const input=JSON.parse(body);calls.push(input.model);res.end(JSON.stringify({id:'response',choices:[{message:{role:'assistant',content:'Fixture '+input.model},finish_reason:'stop'}],usage:{prompt_tokens:3,completion_tokens:2}}));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  await config.commit(0,{type:'setup',provider:{id:'local',adapter:'ollama',name:'Local',baseUrl:'http://127.0.0.1:'+server.address().port+'/v1'},model:{id:'a',providerId:'local',modelId:'fixture-a',tools:false,vision:false,contextWindowTokens:null},key:'fixture-only-credential',dataDir:path.join(root,'数据')});
  const start=await run(['start','--headless']);assert.equal(start.code,0,start.err);info=await connect(config);assert.ok(info);const again=await run(['start','--no-open']);assert.equal(again.code,0,again.err);const same=await connect(config);assert.equal(same.instanceId,info.instanceId);
  const rpc=async(action,data={},protocol=2)=>{const r=await request(info,'POST','/v1/rpc',{id:crypto.randomUUID(),action,protocol,data});assert.equal(r.ok,true,r.error);return r.data;};
  const a=await rpc('session.create',{name:'Before default switch'});const aid=a.session?.id||a.id;assert.ok(aid);const first=await rpc('chat',{sessionId:aid,message:'hello'},1);assert.equal(first.text,'Fixture fixture-a');
  await request(info,'POST','/v1/models',{expectedRevision:1,model:{id:'b',providerId:'local',modelId:'fixture-b',tools:false,vision:false,contextWindowTokens:null}});await request(info,'PUT','/v1/models/default',{expectedRevision:2,id:'b'});
  const existing=await rpc('chat',{sessionId:aid,message:'again'},1);assert.equal(existing.text,'Fixture fixture-a');const b=await rpc('session.create',{name:'After default switch'});const bid=b.session?.id||b.id;const latest=await rpc('chat',{sessionId:bid,message:'hello'},1);assert.equal(latest.text,'Fixture fixture-b');assert.deepEqual(calls,['fixture-a','fixture-a','fixture-b']);
  const replaced=await run(['model','key','replace','local','--credential-stdin','--trust-endpoint'],'dedicated-stdin-fixture');assert.ok(replaced.code===0);assert.ok(!replaced.out.includes('dedicated-stdin-fixture'));const list=await run(['model','list']);assert.equal(list.code,0);assert.ok(!list.out.includes('fixture-only-credential'));const override=await config.commit(3,{type:'model.default',id:'a'}).then(()=>false,e=>e.code==='CONFIG_LOCKED');assert.equal(override,true);
  const stop=await run(['stop']);assert.equal(stop.code,0,stop.err);info=null;await new Promise(r=>setTimeout(r,500));assert.ok(fs.existsSync(path.join(cfg,'config.env')));assert.ok(fs.existsSync(path.join(root,'数据','runtime.sqlite'))||fs.existsSync(path.join(root,'数据','runtime','runtime.sqlite')));
});
