import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';import { createInterface } from 'node:readline';import { randomUUID } from 'node:crypto';import { join, resolve, dirname } from 'node:path';import { fileURLToPath } from 'node:url';import { existsSync, unlinkSync } from 'node:fs';
import { ConfigService, FileLock, atomicPrivate, fail, ConfigError, presets } from '../config/config-service.js';import { ManagementService } from '../config/management-service.js';import { ManagementHttp, type RpcRequest } from '../config/http-server.js';
const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
export function childEnvironment(config:ConfigService,core=true){const env:NodeJS.ProcessEnv={};for(const [k,v]of Object.entries(process.env)){if(/^(PATH|Path|SystemRoot|WINDIR|COMSPEC|PATHEXT|TEMP|TMP|USERPROFILE|HOMEDRIVE|HOMEPATH|LOCALAPPDATA|APPDATA|LANG|NODE_ENV|HTTPS_PROXY|HTTP_PROXY|NO_PROXY)$/.test(k)||(/^SKF_/.test(k)&&!/(KEY|CREDENTIAL|SECRET|TOKEN|PASSWORD)/.test(k)))env[k]=v;}for(const p of config.read().providers){if(p.credentialRef&&process.env[p.credentialRef])env[p.credentialRef]=process.env[p.credentialRef];const preset=presets[p.adapter];const key=config.credential(p);if(preset&&preset.alias&&key)env[preset.alias]=key;}const paths=config.paths();if(!core)return env;return{...env,SKF_MANAGED_INSTANCE:'1',SKF_CONFIG_DIR:config.dir,SKF_DATA_DIR:paths.dataDir,SKF_MEMORY_ROOT:paths.memoryRoot,SKF_SKIP_ENV:'1'};}
class Core {
  private child:ChildProcessWithoutNullStreams|null=null;private pending=new Map<string,{resolve:(v:unknown)=>void;reject:(e:unknown)=>void;timer:NodeJS.Timeout}>();ready=false;
  async start(config:ConfigService){if(this.child)return;const child=spawn(process.execPath,[join(packageRoot,'dist/supervisor.js'),'--ipc'],{cwd:packageRoot,env:childEnvironment(config),windowsHide:true,stdio:['pipe','pipe','pipe']});this.child=child;
    // No raw child stderr/SDK errors in support logs. Diagnostics report stable codes only.
    child.stderr.resume();const lines=createInterface({input:child.stdout});lines.on('line',line=>{if(line.length>1048576)return;let r:{id?:string;event?:unknown};try{r=JSON.parse(line);}catch{return;}if(!r.id)return;const p=this.pending.get(r.id);if(p){clearTimeout(p.timer);this.pending.delete(r.id);p.resolve(r);}});child.once('exit',()=>{this.ready=false;this.child=null;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new ConfigError('CORE_EXITED'));}this.pending.clear();});child.once('error',()=>{this.ready=false;});
    const reply=await this.rpc({id:randomUUID(),action:'ping',protocol:2}) as {ok:boolean};if(!reply.ok)fail('CORE_NOT_READY');this.ready=true;
  }
  rpc(req:RpcRequest):Promise<unknown>{if(!this.child)fail('CORE_NOT_READY');if(typeof req.id!=='string'||req.id.length>80||typeof req.action!=='string'||JSON.stringify(req).length>65536)fail('INVALID_INPUT');if(this.pending.has(req.id))fail('REQUEST_IN_PROGRESS');if(this.pending.size>=64)fail('BUSY');return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(req.id);reject(new ConfigError('CORE_TIMEOUT'));},req.action==='chat'?300000:20000);this.pending.set(req.id,{resolve,reject,timer});this.child!.stdin.write(JSON.stringify(req)+'\n');});}
  async stop(){if(!this.child)return;if(this.pending.size)fail('TASKS_IN_PROGRESS');const ping=await this.rpc({id:randomUUID(),action:'ping',protocol:2}) as {ok:boolean;data?:{busy?:boolean}};if(!ping.ok||ping.data?.busy)fail('TASKS_IN_PROGRESS');const list=await this.rpc({id:randomUUID(),action:'lifecycle.stop-ready'}) as {ok:boolean;data?:{ready:boolean}};if(!list.ok||!list.data?.ready)fail('TASKS_IN_PROGRESS');const child=this.child;await new Promise<void>((ok,no)=>{const timer=setTimeout(()=>no(new ConfigError('CORE_STOP_TIMEOUT')),10000);child.once('exit',()=>{clearTimeout(timer);ok();});child.kill('SIGTERM');});}
}
export async function serve(config:ConfigService){
  await config.ownWriter();try{await config.bootstrapFromLegacy();}catch{/* best-effort legacy migration */}const core=new Core();let closing=false;let runtimeError:string|null=null;
  const ensureCore=async()=>{config.checkDataDir(config.paths().dataDir);try{await core.start(config);runtimeError=null;}catch(e){runtimeError=e instanceof ConfigError?e.code:'CORE_NOT_READY';throw e;}};
  let http:ManagementHttp;let end:()=>void=()=>{};const finished=new Promise<void>(r=>end=r);
  const cleanup=async()=>{if(closing)return;closing=true;try{await core.stop();}catch(e){closing=false;throw e;}setImmediate(()=>{void http.close().finally(()=>{try{const f=join(config.dir,'instance.json');if(existsSync(f))unlinkSync(f);}finally{config.releaseWriter();end();}});});};
  const management=new ManagementService(config,async()=>{try{await ensureCore();}catch{/* configuration saved; handshake exposes runtimeError without raw text */}});
  http=new ManagementHttp(management,{uiDir:join(packageRoot,'ui-preview'),rpc:async req=>{if(closing)fail('INSTANCE_STOPPING');await ensureCore();return core.rpc(req);},stop:cleanup,state:()=>({coreReady:core.ready,configured:!!config.read().defaultModelRef,runtimeError})});
  try{const info=await http.listen();await atomicPrivate(join(config.dir,'instance.json'),JSON.stringify(info));try{await ensureCore();}catch{/* core start failure is surfaced via runtimeError; keep daemon alive */}const onSignal=()=>{void cleanup().catch(()=>{runtimeError='TASKS_IN_PROGRESS';});};process.on('SIGINT',onSignal);process.on('SIGTERM',onSignal);await finished;process.off('SIGINT',onSignal);process.off('SIGTERM',onSignal);}catch(e){await http.close();config.releaseWriter();throw e;}
}
