#!/usr/bin/env node
import { spawn } from 'node:child_process';import { createInterface } from 'node:readline';import { stdin,stdout } from 'node:process';import { randomUUID } from 'node:crypto';import { existsSync } from 'node:fs';import { dirname,join,resolve } from 'node:path';import { fileURLToPath } from 'node:url';
import { ConfigService,ConfigError,fail,MANAGEMENT_PROTOCOL,securePath } from './config/config-service.js';import { connect,managementClient,request, type InstanceInfo } from './cli/client.js';import { onboard,modelCommand } from './cli/manage.js';import { serve,childEnvironment } from './cli/daemon.js';
const entry=fileURLToPath(import.meta.url),root=resolve(dirname(entry),'..');
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function ensureStarted(config:ConfigService,allowSetup=false):Promise<InstanceInfo>{
  let info=await connect(config);if(info)return info;
  if(!config.read().defaultModelRef&&!allowSetup)fail('SETUP_REQUIRED');
  const paths=config.paths();
  const spawnArgs=[entry,'_serve','--config-dir',config.dir,...(paths.source==='parameter'?['--data-dir',paths.dataDir]:[])];
  const child=spawn(process.execPath,spawnArgs,{cwd:root,env:childEnvironment(config,false),detached:true,windowsHide:true,stdio:'ignore'});child.unref();
  for(let i=0;i<80;i++){await sleep(250);try{info=await connect(config);if(info)return info;}catch(e){if(e instanceof ConfigError&&['MANAGEMENT_PROTOCOL_UNSUPPORTED','CONFIG_SCHEMA_UNSUPPORTED'].includes(e.code))throw e;}}
  fail('INSTANCE_START_FAILED');
}
async function doctor(config:ConfigService){const checks:Array<{id:string;ok:boolean;status:string;fix?:string}>=[];const [major,minor]=process.versions.node.split('.').map(Number);checks.push({id:'node',ok:major===24&&minor>=20,status:process.version,fix:'Use Node 24.20.0 or a later Node 24 patch tested by this project.'});try{const {DatabaseSync}=await import('node:sqlite');const db=new DatabaseSync(':memory:');db.exec('CREATE VIRTUAL TABLE probe USING fts5(text)');db.close();checks.push({id:'sqlite',ok:true,status:'SQLite/FTS5 available'});}catch{checks.push({id:'sqlite',ok:false,status:'SQLITE_UNAVAILABLE'});}let status:unknown;try{status=config.status();for(const p of [config.dir,join(config.dir,'config.env')])if(existsSync(p))securePath(p,true);checks.push({id:'config',ok:true,status:'Read and ACL checked; no credentials exported'});}catch(e){checks.push({id:'config',ok:false,status:e instanceof ConfigError?e.code:'CONFIG_INVALID'});}let info:InstanceInfo|null=null;try{info=await connect(config);checks.push({id:'instance',ok:true,status:info?'running; authenticated protocol handshake':'stopped'});}catch(e){checks.push({id:'instance',ok:false,status:e instanceof ConfigError?e.code:'INSTANCE_INVALID'});}const shim=process.platform==='win32'?'skf.cmd':'skf';const pathFound=(process.env.PATH||process.env.Path||'').split(process.platform==='win32'?';':':').some(p=>existsSync(join(p,shim)));checks.push({id:'path',ok:pathFound,status:pathFound?'CLI shim on PATH':'CLI shim not found on PATH',fix:'Use user-level npm prefix and reopen terminal. On PowerShell use skf.cmd / npm.cmd; do not change execution policy.'});checks.push({id:'desktop',ok:true,status:process.platform==='win32'&&existsSync(join(root,'bin','UiaHelper.exe'))?'Helper present; optional interactive-desktop capability requires independent verification':'Desktop unavailable; CLI/Web do not require WebView2'});console.log(JSON.stringify({ok:checks.every(c=>c.ok),checks,configuration:status,diagnosticExclusions:['config.env','instance.json','process environment','request headers','raw provider responses','heap dumps']},null,2));if(checks.some(c=>!c.ok))process.exitCode=1;}
async function bridge(config:ConfigService){const info=await ensureStarted(config,true);const lines=createInterface({input:stdin,crlfDelay:Infinity});const pending=new Set<Promise<void>>();for await(const line of lines){if(line.length>65536)continue;const work=(async()=>{let id='';try{const req=JSON.parse(line);id=typeof req.id==='string'?req.id:'';let result:unknown;if(req.action==='management'){const d=req.data||{};if(d.protocol!==MANAGEMENT_PROTOCOL)fail('MANAGEMENT_PROTOCOL_UNSUPPORTED');result={id,ok:true,data:await request(info,d.method,d.path,d.body),error:null};}else result=await request(info,'POST','/v1/rpc',req);stdout.write(JSON.stringify(result)+'\n');}catch(e){stdout.write(JSON.stringify({id,ok:false,data:null,error:e instanceof ConfigError?e.code:'REQUEST_FAILED'})+'\n');}})();pending.add(work);void work.finally(()=>pending.delete(work));if(pending.size>=32)await Promise.race(pending);}await Promise.all(pending);}
async function main(){
  const args=process.argv.slice(2);if(args.some(a=>/^--.*(key|token|secret|password)/i.test(a)))fail('SECRET_ARGUMENT_FORBIDDEN');
  const option=(flag:string)=>{const i=args.indexOf(flag);if(i<0)return undefined;const v=args[i+1];if(!v||v.startsWith('--'))fail('CLI_USAGE');args.splice(i,2);return v;};const configDir=option('--config-dir'),dataDir=option('--data-dir');const config=new ConfigService({configDir,dataDir});const command=args.shift()||'help';
  if(command==='_serve'){await serve(config);return;}if(command==='bridge'){await bridge(config);return;}
  if(command==='onboard'){await onboard(await managementClient(config),args.includes('--force'));return;}
  if(command==='model'){await modelCommand(args,await managementClient(config));return;}
  if(command==='doctor'){await doctor(config);return;}
  if(command==='status'){const info=await connect(config);const status=info?await request(info,'GET','/v1/setup/status'):config.status();console.log(JSON.stringify({running:!!info,...status as object,...(info?{url:info.url,handshake:await request(info,'GET','/v1/handshake')}:{})},null,2));return;}
  if(command==='start'){
    if(!config.read().defaultModelRef){if(!stdin.isTTY)fail('SETUP_REQUIRED');await onboard(await managementClient(config));}
    if(args.includes('--foreground')){console.log('Supervisor foreground; use skf status for authenticated instance state.');await serve(config);return;}
    const info=await ensureStarted(config);console.log('SKF local UI: '+info.url);console.log('No automatic tool authorization or publication permission was granted.');
    if(!args.includes('--headless')&&!args.includes('--no-open')&&stdout.isTTY){const pairing=await request(info,'POST','/v1/pairing/new',{}) as {code:string};console.log('One-time browser pairing code (expires in 120s): '+pairing.code);if(process.platform==='win32'){const p=spawn('rundll32.exe',['url.dll,FileProtocolHandler',info.url],{stdio:'ignore',windowsHide:true});p.unref();}}return;
  }
  if(command==='pair'){const info=await connect(config)||fail('INSTANCE_NOT_RUNNING');if(!stdout.isTTY)fail('TTY_REQUIRED');const pairing=await request(info,'POST','/v1/pairing/new',{}) as {code:string};console.log('Local UI: '+info.url+'\nOne-time code (120s): '+pairing.code);return;}
  if(command==='stop'){const info=await connect(config);if(!info){console.log('SKF is stopped.');return;}await request(info,'POST','/v1/stop',{});console.log('SKF stopped; data and credentials retained.');return;}
  if(command==='chat'){const info=await connect(config)||fail('INSTANCE_NOT_RUNNING');if(!stdin.isTTY)fail('TTY_REQUIRED');const call=async(action:string,data:Record<string,unknown>,protocol?:number)=>{const reply=await request(info,'POST','/v1/rpc',{id:randomUUID(),action,data,...(protocol?{protocol}:{})}) as {ok:boolean;data:Record<string,unknown>;error?:string};if(!reply.ok)fail(reply.error||'REQUEST_FAILED');return reply.data;};const s=await call('session.create',{name:'Terminal '+new Date().toISOString()},2);const sessionId=(s.session as {id?:string}|undefined)?.id||(s.id as string);if(!sessionId)fail('INSTANCE_PROTOCOL_INVALID');const rl=createInterface({input:stdin,output:stdout});console.log('Chat (/exit to leave). Model calls can incur charges; E/P approval remains enforced.');rl.prompt();for await(const message of rl){if(message==='/exit')break;if(!message.trim()){rl.prompt();continue;}try{const r=await call('chat',{sessionId,message});console.log(r.state==='waiting_approval'?'Waiting for approval in the local UI. No external action approved automatically.':String(r.text||''));}catch(e){console.error(e instanceof ConfigError?e.code:'REQUEST_FAILED');}rl.prompt();}rl.close();return;}
  console.log('SKF\n  onboard [--force]\n  start [--no-open|--headless|--foreground]\n  status | stop | chat | doctor | pair\n  model add|list|remove <id>|set-default <id>|test <id>|edit <id>\n  model key replace <provider-id>\n  model provider remove <provider-id>\n  --config-dir <path> [--data-dir <path>]\nCredentials: hidden local input only; no plaintext key arguments.');if(command!=='help'&&command!=='--help')process.exitCode=2;
}
main().catch(e=>{console.error(e instanceof ConfigError?e.code:'SKF_COMMAND_FAILED');process.exitCode=1;});
